<?php
/**
 * @file
 * This module can export and import datasets.
 *
 * It will have several clearly defined sections and will be
 * extended by  plugins or include files.
 *
 * The sections are:
 * Help
 * Permissions
 * hook_menu
 * calbacks
 * forms
 * submit
 * validation
 */

/**
 * Display help and module information
 *
 * @param string $path
 *   Path which path of the site we're displaying help.
 * @param array $arg
 *   Arg array that holds the current path as would be returned from
 *   arg() function.
 *
 * @return string
 *   Help text for the path.
 */
function data_export_import_help($path, $arg) {

  $output = '';

  switch ($path) {
    case "admin/help#data_export_import":
      $output = '<p>' . t("Exports datasets as files which can then imported into other Drupal instances.") . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_perm().
 */
function data_export_import_perm() {
  return array('access data export import');
}

/**
 * This is the hook_menu section.
 *
 * Defines all pages and tabs.
 */
function data_export_import_menu() {

  $items = array();

  $items['admin/content/data_export_import'] = array(
    'title' => 'Data export import',
    'page callback' => 'data_export_import_callback_export',
    'access arguments' => array('access data export import'),
    'description' => 'Data export import',
    'type' => MENU_NORMAL_ITEM,
  );

  // This 'tab' inherits from MENU_NORMAL_ITEM
  $items['admin/content/data_export_import/export'] = array(
    'title' => 'Export',
    'weight' => 0,
    'description' => 'Data export import',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/content/data_export_import/import'] = array(
    'title' => 'Import',
    'page callback' => 'data_export_import_callback_import',
    'access arguments' => array('access data export import'),
    'weight' => 1,
    'description' => 'Import dataset files',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Callback function for exporting datasets.
 *
 * @return string
 *   Form to enable the user to select datasets for exporting.
 */
function data_export_import_callback_export() {

  // This form calls the form builder function via the
  // drupal_get_form() function which takes the name of this form builder
  // function as an argument. It returns the results to display the form.
  return drupal_get_form('data_export_import_export_form');
}

/**
 * Callback function for importing datasets.
 *
 * @return string
 *   Form to enable the user to select datasets for importing.
 */
function data_export_import_callback_import() {

  // This form calls the form builder function via the
  // drupal_get_form() function which takes the name of this form builder
  // function as an argument. It returns the results to display the form.
  return drupal_get_form('data_export_import_import_form');
}

/**
 * Create form to enable users to be able to select datasets to export.
 *
 * @param array $form_state
 *   The current values of the form elements.
 *
 * @return array
 *   The form elements to enable the user to choose which datasets to export.
 */
function data_export_import_export_form($form_state) {

  // Pages.
  $form['pages'] = array(
    '#type' => 'fieldset',
    '#title' => t('Pages'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['pages']['pages'] = array(
    '#type' => 'checkbox',
    '#title' => t('Export all Pages'),
  );

  // Taxonomy terms.
  $form['taxonomy_terms'] = array(
    '#type' => 'fieldset',
    '#title' => t('Taxonomy terms'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['taxonomy_terms']['taxonomy_terms'] = array(
    '#type' => 'checkbox',
    '#title' => t('Export all Taxonomy terms'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Create dataset files',
  );

  return $form;
}

/**
 * Create form to enable users to be able to select datasets to import.
 *
 * @param array $form_state
 *   The current values of the form elements.
 *
 * @return array
 *   The form elements to enable the user to choose which datasets to export.
 */
function data_export_import_import_form($form_state) {

  $form = array();

  // Pages
  $form['pages'] = array(
    '#type' => 'fieldset',
    '#title' => t('Pages'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $directory = file_directory_path() . '/data_export_import/pages';

  // NB - This will only produce TRUE if the directory exists and it
  // is writable - so we need to be aware of this returning false if
  // the directory was created during testing and it is not writable
  // by the web server account.
  if (file_check_directory($directory)) {

    $mask = '.dataset';
    $files = file_scan_directory($directory, $mask);

    // Sort them by the filename which is used as the key.
    ksort($files);

    $options = array();
    $options['none'] = "None";
    foreach ($files as $file) {

      $options[$file->basename] = check_plain($file->basename);
    }
  }

  $form['pages']['pages'] = array(
    '#type' => 'radios',
    '#title' => t('Please select file to import'),
    '#default_value' => 'none',
    '#options' => $options,
  );

  // Taxonomy terms
  // -------------------------------------------------------------------
  $form['taxonomy_terms'] = array(
    '#type' => 'fieldset',
    '#title' => t('Taxonomy terms'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  // Get the contents of the dataset directory and create a list of
  // links which can be used to trigger the data import.
  $directory = drupal_get_path('module', 'data_export_import') . '/includes';
  $directory = "sites/default/files/data_export_import/taxonomy_terms";
  $mask = '.dataset';
  $files = file_scan_directory($directory, $mask);

  // Sort them by the filename which is used as the key.
  ksort($files);

  $options = array();
  $options['none'] = "None";
  foreach ($files as $file) {
    $options[$file->basename] = check_plain($file->basename);

  }

  $form['taxonomy_terms']['taxonomy_terms'] = array(
    '#type' => 'radios',
    '#title' => t('Please select file to import'),
    '#default_value' => 'none',
    '#options' => $options,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Import dataset files',
  );

  return $form;
}


/**
 * This is the main function called on the data export form.
 *
 * @param array $form
 *   Form items.
 *
 * @param array &$form_state
 *   Values of form items.
 *
 * @return bool
 *   TRUE if all exports ran without error.
 */
function data_export_import_export_form_submit($form, &$form_state) {

  // Need to include files holding import functions.
  module_load_include('inc', 'data_export_import', 'includes/profiles/pages');
  module_load_include('inc', 'data_export_import', 'includes/profiles/taxonomy_terms');

  // These need to be brought in from the include files.
  // Pages.
  // Case if Pages has been selected.
  if ($form_state['values']['pages'] == 1) {

    $dataset_file = data_export_import_export_pages();
    drupal_set_message(t('The Pages dataset was output to the file: %dataset_file', array('%dataset_file' => $dataset_file)));
  }

  // Taxonomy terms.
  // Case if Taxonomy terms has been selected.
  if ($form_state['values']['taxonomy_terms'] == 1) {

    $dataset_file = data_export_import_export_taxonomy_terms();
    drupal_set_message(t('The Taxonomy Terms dataset was output to the file: %dataset_file', array('%dataset_file' => $dataset_file)));
  }

  return TRUE;
}

/**
 * This is the main function called on the data import form.
 *
 * @param array $form
 *   Form items.
 *
 * @param array &$form_state
 *   Values of form items.
 *
 * @return bool
 *   TRUE if all imports ran without error.
 */
function data_export_import_import_form_submit($form, &$form_state) {

  // include_once 'includes/profiles/pages.inc';
  // include_once 'includes/profiles/taxonomy_terms.inc';
  module_load_include('inc', 'data_export_import', 'includes/profiles/pages');
  module_load_include('inc', 'data_export_import', 'includes/profiles/taxonomy_terms');

  // Pages.
  if ($form_state['clicked_button']['#post']['pages'] != 'none') {

    $result = data_export_import_import_pages($form_state['clicked_button']['#post']['pages']);
    drupal_set_message(t('The Pages dataset file %dataset_file was imported.', array('%dataset_file' => $form_state['clicked_button']['#post']['pages'])));
  }

  // Taxonomy terms.
  if ($form_state['clicked_button']['#post']['taxonomy_terms'] != 'none') {

    $result = data_export_import_import_taxonomy_terms($form_state['clicked_button']['#post']['taxonomy_terms']);
    drupal_set_message(t('The Taxonomy Terms dataset file %dataset_file was imported.', array('%dataset_file' => $form_state['clicked_button']['#post']['taxonomy_terms'])));
  }
}
